In [1]:
import pandas as pd
import numpy as np

In [2]:
df_crimes = pd.read_csv("Crimes_-_One_year_prior_to_present.csv")

In [3]:
df_crimes

,CASE#,DATE OF OCCURRENCE,BLOCK,IUCR,PRIMARY DESCRIPTION,SECONDARY DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,BEAT,WARD,FBI CD,X COORDINATE,Y COORDINATE,LATITUDE,LONGITUDE,LOCATION
0,JE163990,11/23/2020 03:05:00 PM,073XX S SOUTH SHORE DR,0820,THEFT,$500 AND UNDER,APARTMENT,N,N,334,7.0,06,NaN,NaN,NaN,NaN,NaN
1,JE266628,06/15/2021 09:30:00 AM,080XX S DREXEL AVE,0820,THEFT,$500 AND UNDER,STREET,N,N,631,8.0,06,1183633.0,1851786.0,41.748486,-87.602675,"(41.748486365, -87.602675062)"
2,JE266536,06/15/2021 07:50:00 AM,042XX W MADISON ST,0560,ASSAULT,SIMPLE,SIDEWALK,N,N,1115,28.0,08A,1148227.0,1899678.0,41.880661,-87.731186,"(41.880660786, -87.731186405)"
3,JE266663,06/15/2021 08:40:00 AM,044XX N ARTESIAN AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,N,N,1911,47.0,11,NaN,NaN,NaN,NaN,NaN
4,JE266959,06/15/2021 01:30:00 PM,018XX N DAMEN AVE,0460,BATTERY,SIMPLE,PARK PROPERTY,N,N,1434,32.0,08B,1162738.0,1912139.0,41.914563,-87.677553,"(41.914562993, -87.677553434)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202464,JD430516,10/25/2020 12:00:00 PM,029XX N MELVINA AVE,1154,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT $300 AND UNDER,RESIDENCE,N,N,2511,30.0,11,1134560.0,1918918.0,41.933710,-87.780916,"(41.933709921, -87.780916246)"
202465,JD430452,11/07/2020 10:00:00 PM,011XX S MICHIGAN AVE,0281,CRIMINAL SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL / MOTEL,N,N,123,4.0,02,1177417.0,1895669.0,41.869048,-87.624126,"(41.869047845, -87.624125523)"
202466,JD434095,11/17/2020 04:15:00 PM,047XX N KEDZIE AVE,0560,ASSAULT,SIMPLE,SIDEWALK,N,N,1713,33.0,08A,1154189.0,1931371.0,41.967512,-87.708446,"(41.967512085, -87.708446268)"
202467,JD453566,12/08/2020 07:22:00 PM,037XX N RECREATION DR,0486,BATTERY,DOMESTIC BATTERY SIMPLE,PARK PROPERTY,N,Y,1925,46.0,08B,1171826.0,1925510.0,41.951058,-87.643771,"(41.951058037, -87.643770543)"
202468,JD434362,11/17/2020 08:45:00 PM,025XX W FITCH AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,N,Y,2411,50.0,08B,1158111.0,1947358.0,42.011302,-87.693586,"(42.011301687, -87.693586328)"

In [4]:
df_crimes.columns

Index(['CASE#', 'DATE  OF OCCURRENCE', 'BLOCK', ' IUCR',
       ' PRIMARY DESCRIPTION', ' SECONDARY DESCRIPTION',
       ' LOCATION DESCRIPTION', 'ARREST', 'DOMESTIC', 'BEAT', 'WARD', 'FBI CD',
       'X COORDINATE', 'Y COORDINATE', 'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

In [5]:
df_crimes.columns = [x.lstrip().replace(' ', "_").lower() for x in df_crimes.columns]

In [6]:
df_crimes.columns

Index(['case#', 'date__of_occurrence', 'block', 'iucr', 'primary_description',
       'secondary_description', 'location_description', 'arrest', 'domestic',
       'beat', 'ward', 'fbi_cd', 'x_coordinate', 'y_coordinate', 'latitude',
       'longitude', 'location'],
      dtype='object')

In [7]:
df_crimes['date__of_occurrence'] = pd.to_datetime(df_crimes['date__of_occurrence'])

In [8]:
df_crimes = df_crimes.sort_values(by = 'date__of_occurrence').reset_index()

In [9]:
df_crimes['primary_description'].unique()

array(['CRIMINAL DAMAGE', 'BATTERY', 'THEFT', 'ROBBERY', 'OTHER OFFENSE',
       'STALKING', 'DECEPTIVE PRACTICE', 'BURGLARY',
       'MOTOR VEHICLE THEFT', 'SEX OFFENSE', 'ASSAULT', 'NARCOTICS',
       'CRIMINAL TRESPASS', 'PUBLIC PEACE VIOLATION',
       'OFFENSE INVOLVING CHILDREN', 'WEAPONS VIOLATION', 'HOMICIDE',
       'INTIMIDATION', 'ARSON', 'INTERFERENCE WITH PUBLIC OFFICER',
       'CRIMINAL SEXUAL ASSAULT', 'GAMBLING', 'LIQUOR LAW VIOLATION',
       'PROSTITUTION', 'KIDNAPPING', 'CONCEALED CARRY LICENSE VIOLATION',
       'HUMAN TRAFFICKING', 'OBSCENITY', 'PUBLIC INDECENCY',
       'NON-CRIMINAL', 'OTHER NARCOTIC VIOLATION', 'RITUALISM'],
      dtype=object)

In [10]:
df_crimes.groupby('primary_description').count().iloc[:,0]

primary_description
ARSON                                  560
ASSAULT                              18881
BATTERY                              39441
BURGLARY                              6727
CONCEALED CARRY LICENSE VIOLATION      160
CRIMINAL DAMAGE                      24193
CRIMINAL SEXUAL ASSAULT               1243
CRIMINAL TRESPASS                     3448
DECEPTIVE PRACTICE                   19183
GAMBLING                                19
HOMICIDE                               778
HUMAN TRAFFICKING                        5
INTERFERENCE WITH PUBLIC OFFICER       408
INTIMIDATION                           154
KIDNAPPING                             103
LIQUOR LAW VIOLATION                   143
MOTOR VEHICLE THEFT                  10188
NARCOTICS                             5565
NON-CRIMINAL                             4
OBSCENITY                               53
OFFENSE INVOLVING CHILDREN            1795
OTHER NARCOTIC VIOLATION                 3
OTHER OFFENSE                        13251
PROSTITUTION                           161
PUBLIC INDECENCY                         8
PUBLIC PEACE VIOLATION                 664
RITUALISM                                1
ROBBERY                               7652
SEX OFFENSE                            918
STALKING                               277
THEFT                                37026
WEAPONS VIOLATION                     9457
Name: index, dtype: int64

In [11]:
df_violent_crimes = df_crimes[~df_crimes['primary_description'].isin(['DECEPTIVE PRACTICE','OTHER OFFENSE','WEAPONS VIOLATION','CRIMINAL TRESPASS',
                                                                      'NARCOTICS','PUBLIC PEACE VIOLATION', 'PROSTITUTION',
                                                                      'INTERFERENCE WITH PUBLIC OFFICER', 'INTIMIDATION','CONCEALED CARRY LICENSE VIOLATION',
                                                                      'LIQUOR LAW VIOLATION', 'OTHER NARCOTIC VIOLATION', 'OBSCENITY','PUBLIC INDECENCY', 'NON-CRIMINAL',
                                                                      'GAMBLING', 'RITUALISM'])]

In [12]:
df_max_temps = pd.read_csv("ChicagoMaxTemps.csv")[['Date',"Maximum Temperature"]].dropna()

In [13]:
df_violent_crimes['Date'] = df_violent_crimes.date__of_occurrence.dt.date

<ipython-input-13-576d5b63f243>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_violent_crimes['Date'] = df_violent_crimes.date__of_occurrence.dt.date

In [14]:
df_max_temps["Date"] = pd.to_datetime(df_max_temps["Date"])

In [15]:
df_violent_crimes['Date'] = df_violent_crimes.Date.astype('datetime64[ns]')
df_max_temps['Date'] = df_max_temps.Date.astype('datetime64[ns]')

<ipython-input-15-b86e14a3cd1a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_violent_crimes['Date'] = df_violent_crimes.Date.astype('datetime64[ns]')

In [16]:
df_crimes_temp = df_violent_crimes.merge(df_max_temps, on="Date")

In [17]:
df_crimes_temp

,index,case#,date__of_occurrence,block,iucr,primary_description,secondary_description,location_description,arrest,domestic,beat,ward,fbi_cd,x_coordinate,y_coordinate,latitude,longitude,location,Date,Maximum Temperature
0,138388,JD295526,2020-07-13 05:04:00,038XX W 16TH ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,N,N,1014,24.0,14,1151169.0,1891774.0,41.858914,-87.720591,"(41.858914162, -87.720590723)",2020-07-13,84.0
1,138442,JD295532,2020-07-13 05:05:00,051XX W FLETCHER ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,Y,Y,2521,31.0,08B,1141575.0,1920458.0,41.937809,-87.755098,"(41.937808906, -87.75509789)",2020-07-13,84.0
2,138342,JD295531,2020-07-13 05:09:00,011XX W 63RD ST,0860,THEFT,RETAIL THEFT,GAS STATION,N,N,724,16.0,06,1169601.0,1863016.0,41.779618,-87.653768,"(41.779618399, -87.653767961)",2020-07-13,84.0
3,138257,JD295528,2020-07-13 05:10:00,061XX S EBERHART AVE,0460,BATTERY,SIMPLE,SIDEWALK,N,N,313,20.0,08B,1180634.0,1864497.0,41.783436,-87.613274,"(41.783436023, -87.613274426)",2020-07-13,84.0
4,138016,JD295534,2020-07-13 05:20:00,0000X W CTA 69TH ST LN,0330,ROBBERY,AGGRAVATED,CTA PLATFORM,N,N,322,6.0,03,1177340.0,1859132.0,41.768789,-87.625513,"(41.768788957, -87.625513163)",2020-07-13,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95587,130241,JE299634,2021-07-12 23:45:00,101XX S DR MARTIN LUTHER KING JR DR,051A,ASSAULT,AGGRAVATED - HANDGUN,RESIDENCE,N,Y,511,9.0,04A,1180704.0,1837730.0,41.709983,-87.613838,"(41.70998275, -87.613838374)",2021-07-12,74.0
95588,129282,JE299937,2021-07-12 23:51:00,012XX W 57TH ST,031A,ROBBERY,ARMED - HANDGUN,STREET,N,N,713,16.0,03,1168870.0,1866977.0,41.790504,-87.656334,"(41.790503678, -87.656333559)",2021-07-12,74.0
95589,130039,JE299567,2021-07-12 23:51:00,014XX W 62ND ST,051A,ASSAULT,AGGRAVATED - HANDGUN,STREET,N,N,713,16.0,04A,1167621.0,1863627.0,41.781338,-87.661009,"(41.781337768, -87.661009376)",2021-07-12,74.0
95590,129917,JE299560,2021-07-12 23:55:00,043XX S WOOD ST,051A,ASSAULT,AGGRAVATED - HANDGUN,STREET,N,N,924,15.0,04A,1165077.0,1875815.0,41.814837,-87.669991,"(41.814837319, -87.669991445)",2021-07-12,74.0
95591,129261,JE299563,2021-07-12 23:57:00,0000X W 79TH ST,0331,ROBBERY,ATTEMPT AGGRAVATED,SIDEWALK,N,N,623,6.0,03,1177483.0,1852629.0,41.750941,-87.625185,"(41.750940757, -87.625185222)",2021-07-12,74.0

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [19]:
df_crimes_temp[['x_coordinate', 'y_coordinate', 'latitude', 'longitude', 'Maximum Temperature']].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 95592 entries, 0 to 95591
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   x_coordinate         94726 non-null  float64
 1   y_coordinate         94726 non-null  float64
 2   latitude             94726 non-null  float64
 3   longitude            94726 non-null  float64
 4   Maximum Temperature  95592 non-null  float64
dtypes: float64(5)
memory usage: 4.4 MB

In [20]:
df_crimes_temp['homicide'] = df_crimes_temp['primary_description'] == 'HOMICIDE'

In [21]:
df_crimes_temp['homicide'].value_counts()

False    95068
True       524
Name: homicide, dtype: int64

In [22]:
features = df_crimes_temp[['x_coordinate', 'y_coordinate', 'latitude', 'longitude', 'homicide']].dropna()
x = features[['x_coordinate', 'y_coordinate', 'latitude', 'longitude']]
y = features['homicide']

In [23]:
rf = RandomForestClassifier(n_estimators=20)
np.mean(cross_val_score(rf, x, y, cv=5))

0.9934125789909437

In [24]:
features = df_crimes_temp[['x_coordinate', 'y_coordinate', 'latitude', 'longitude', 'Maximum Temperature', 'homicide']].dropna()
x = features[['x_coordinate', 'y_coordinate', 'latitude', 'longitude', 'Maximum Temperature']]
y = features['homicide']

In [25]:
rf = RandomForestClassifier(n_estimators=20)
np.mean(cross_val_score(rf, x, y, cv=5))

0.9941198834977001

In [26]:
df_crimes_temp.groupby('Maximum Temperature').sum()['homicide']

Maximum Temperature
38.0     1
39.0     0
40.0     1
43.0     0
44.0     1
47.0     5
49.0    10
50.0     4
51.0     6
52.0     1
53.0     2
54.0     5
55.0     3
56.0     9
57.0     6
58.0     0
59.0     8
60.0    11
61.0     4
62.0    15
63.0     6
64.0     5
65.0     7
67.0     6
68.0     3
69.0     5
70.0     7
71.0     6
72.0     7
73.0    20
74.0     1
75.0     8
76.0    35
77.0    30
78.0     8
79.0    23
80.0    16
81.0     4
82.0    32
83.0    22
84.0    10
85.0    18
86.0    26
87.0    15
88.0    17
89.0    21
90.0    21
91.0    22
92.0    11
93.0     5
94.0     4
95.0     9
96.0     2
97.0     0
Name: homicide, dtype: int64